  radio_station:
    name: "Select Radio Station:"
    options:
      - Radio Comercial
      - RFM
      - M80
      - CidadeFM
      - Smooth FM

  chromecast_radio:
    name: "Select Speakers:"
    options:
      - Sala
      - Suite
      - Escritorio
      - Cozinha
      - Guest room
      - Everywhere
    initial: Everywhere
    icon: mdi:speaker-wireless

input_number:
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05

script: !include scripts.yaml